[package]
name = "native_app"
version = "0.4.3"
authors = ["Douady Pâris <paris.douady@hotmail.fr>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

futures       = { version = "0.3.4", default-features = false, features = ["executor"] }
bytemuck      = "1.7.2"
egregoria     = { path = "../egregoria" }
geom          = { path = "../geom" }
wgpu_engine   = { path = "../wgpu_engine" }
common        = { path = "../common" }
networking    = { path = "../networking", optional=true }
flat_spatial  = "0.5.0"
log           = { version = "0.4.11", features=["max_level_debug", "release_max_level_info"] }
inline_tweak  = "1.0.6"
hecs          = "0.9.0"
resources     = "1.1.0"
ordered-float = { version = "2.7.0", default-features = false }
serde         = "1.0"
oddio         = "0.5.0"
cpal          = "0.13.5"
lewton        = "0.10.2"
slotmap       = { version = "1.0.2", default-features = false }
winit         = "0.27.2"
paste         = "1.0.4"
atomic_refcell = "0.1.6"
rayon         = "1.5.3"
profiling     = "1.0.1"
include_dir   = "0.7.2"
egui-inspect = { path = "../egui-inspect" }
egui-inspect-derive = { path = "../egui-inspect-derive" }
egui = { version = "0.19.0", default-features = false }
egui-winit = "0.19.0"
egui-wgpu = "0.19.0"

[features]
default = []
enable_profile = ["profiling/profile-with-tracy"]
multiplayer = ["networking"]