[workspace]
members = [
    "common",
    "egregoria",
    "egui-inspect",
    "egui-inspect-derive",
    "geom",
    "headless",
    "native_app",
    "networking",
    "wgpu_engine",
    "wgpu_engine_demo",
]

resolver = "2"
default-members = ["native_app"]

[workspace.dependencies]
hecs = "0.10.0"
egui = { git = "https://github.com/emilk/egui", branch = "master" }
flat_spatial = "0.5.1"
egui-wgpu = { git = "https://github.com/emilk/egui", branch = "master" }
egui_extras = { git = "https://github.com/emilk/egui", branch = "master" }
egui-winit = { git = "https://github.com/emilk/egui", branch = "master", default-features = false }

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.dev.package.common]
opt-level = 2

[profile.dev.package.egregoria]
opt-level = 1

[profile.dev.package.native_app]
opt-level = 1

[profile.dev.package.egui-inspect]
opt-level = 1

[profile.dev.package.egui-inspect-derive]
opt-level = 1

[profile.release]
#debug = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
