[package]
name = "egregoria"
version = "0.1.0"
authors = ["Douady Pâris <paris.douady@hotmail.fr>"]
edition = "2018"

# Yes I have many dependencies.
# Yes, I know it takes a while to compile.
# However, it slows me down, and there's incremental compilation.
# I'll prune some of them when I feel it's worth it.

[dependencies]
ordered-float = { version = "2.0", features = ["serde"] }
rand          = { version = "0.8", default-features = false, features = ["small_rng"] }
rand_distr    = "0.4"
serde         = "1.0"
legion        = { version = "0.4.0", default-features = false, features = ["codegen", "serialize", "parallel"] }
log           = "0.4.11"
imgui-inspect = { path = "../imgui-inspect"}
imgui-inspect-derive = { path = "../imgui-inspect-derive" }
flat_spatial  = { path = "../flat_spatial" }
geom          = { path = "../geom" }
map_model     = { path = "../map_model" }
mods          = { path = "../mods" }
common        = { path = "../common" }
slotmap       = { version = "1.0.2", default-features = false }
dashmap       = { version = "4.0.2", features = ["serde"] }
imgui         = "0.7"
rayon         = "1.5.0"
inventory     = "0.1.10"
paste         = "1.0.4"
atomic_refcell = "0.1.6"